#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 17 12:07:48 2023

@author: jeet
"""
import sys

input_top_file = sys.argv[1] #'in_converted.top' # "Input top file generated by intermol"
output_top_file = input_top_file.split('.')[0] + '_formatted.top'

conversion_dict_atom_name={
    'lmp_001': 'K',
    'lmp_002': 'BR'
    }

f = open(input_top_file, 'r')
lines = f.readlines()

modified_lines = []
for line in lines:
    if 'R01' in line:
        words = line.split()
        atom_number=int(words[0])
        atom_type = words[1]
        resnum = words[2]
        resname = words[3]
        atom_name = conversion_dict_atom_name[atom_type]
        cgnr = words[5]
        q = words[6]
        m = words[7]
        line = f'{atom_number:>6d} {atom_type} {resnum:>10s} {resname:10s} {atom_name} {cgnr:>6s} {q:>25s} {m:>25s}\n'
        
    modified_lines.append(line)

f.close()

f = open(output_top_file, 'w')
for i in modified_lines:
    f.write(i)
f.close()
