from intermol.forces.bond import Bond
from intermol.forces.angle import Angle
from intermol.forces.dihedral import Dihedral

from intermol.forces.abstract_atom_type import AbstractAtomType
from intermol.forces.abstract_nonbonded_type import AbstractNonbondedType
from intermol.forces.abstract_bond_type import AbstractBondType
from intermol.forces.abstract_pair_type import AbstractPairType
from intermol.forces.abstract_angle_type import AbstractAngleType
from intermol.forces.abstract_dihedral_type import AbstractDihedralType
from intermol.forces.abstract_virtual_type import AbstractVirtualType

# atom types
from intermol.forces.atom_c_type import AtomCType
from intermol.forces.atom_sigeps_type import AtomSigepsType
AbstractAtomType.subtypes = [AtomCType, AtomSigepsType]

#settles
from intermol.forces.settles import Settles

# what is below here really should be written automatically
# nonbonded
from intermol.forces.lj_c_nonbonded_type import LjCNonbondedType
from intermol.forces.lj_sigeps_nonbonded_type import LjSigepsNonbondedType
from intermol.forces.buckingham_nonbonded_type import BuckinghamNonbondedType
AbstractNonbondedType.subtypes = [LjCNonbondedType, LjSigepsNonbondedType, BuckinghamNonbondedType]

#pairs
from intermol.forces.lj_c_pair_type import LjCPairType
from intermol.forces.lj_sigeps_pair_type import LjSigepsPairType
from intermol.forces.ljq_c_pair_type import LjqCPairType
from intermol.forces.ljq_sigeps_pair_type import LjqSigepsPairType
from intermol.forces.lj_default_pair_type import LjDefaultPairType
from intermol.forces.ljq_default_pair_type import LjqDefaultPairType
AbstractPairType.subtypes = [LjCPairType, LjSigepsPairType, LjqCPairType, LjqSigepsPairType, LjDefaultPairType, LjqDefaultPairType]

#bonds
from intermol.forces.connection_bond_type import ConnectionBondType
from intermol.forces.cubic_bond_type import CubicBondType
from intermol.forces.fene_bond_type import FeneBondType
from intermol.forces.fene_expandable_bond_type import FeneExpandableBondType
from intermol.forces.g96_bond_type import G96BondType
from intermol.forces.harmonic_bond_type import HarmonicBondType
from intermol.forces.harmonic_potential_bond_type import HarmonicPotentialBondType
from intermol.forces.morse_bond_type import MorseBondType
from intermol.forces.nonlinear_bond_type import NonlinearBondType
from intermol.forces.quartic_breakable_bond_type import QuarticBreakableBondType
from intermol.forces.quartic_bond_type import QuarticBondType
AbstractBondType.subtypes = [ConnectionBondType, CubicBondType, FeneBondType, FeneExpandableBondType, G96BondType, HarmonicBondType, HarmonicPotentialBondType, MorseBondType, NonlinearBondType, QuarticBreakableBondType, QuarticBondType]

#angles
from intermol.forces.cross_bond_angle_angle_type import CrossBondAngleAngleType
from intermol.forces.cross_bond_bond_angle_type import CrossBondBondAngleType
from intermol.forces.cosine_angle_type import CosineAngleType
from intermol.forces.cosine_squared_angle_type import CosineSquaredAngleType
from intermol.forces.harmonic_angle_type import HarmonicAngleType
from intermol.forces.quartic_angle_type import QuarticAngleType
from intermol.forces.urey_bradley_angle_type import UreyBradleyAngleType
AbstractAngleType.subtypes = [ CrossBondAngleAngleType, CrossBondBondAngleType, CosineAngleType, CosineSquaredAngleType, HarmonicAngleType, QuarticAngleType, UreyBradleyAngleType]

#dihedrals
from intermol.forces.fourier_dihedral_type import FourierDihedralType
from intermol.forces.improper_harmonic_dihedral_type import ImproperHarmonicDihedralType
from intermol.forces.proper_periodic_dihedral_type import ProperPeriodicDihedralType
from intermol.forces.rb_dihedral_type import RbDihedralType
from intermol.forces.trig_dihedral_type import TrigDihedralType
AbstractDihedralType.subtypes = [ FourierDihedralType, ImproperHarmonicDihedralType, ProperPeriodicDihedralType, RbDihedralType, TrigDihedralType]

# virtual_sites
from intermol.forces.two_virtual_type import TwoVirtualType
from intermol.forces.three_linear_virtual_type import ThreeLinearVirtualType
from intermol.forces.three_fd_virtual_type import ThreeFdVirtualType
from intermol.forces.three_fad_virtual_type import ThreeFadVirtualType
from intermol.forces.three_out_virtual_type import ThreeOutVirtualType
from intermol.forces.four_fdn_virtual_type import FourFdnVirtualType
AbstractVirtualType.subtypes = [TwoVirtualType, ThreeLinearVirtualType, ThreeFdVirtualType, ThreeFadVirtualType, ThreeOutVirtualType, FourFdnVirtualType]

# dihedral conversion
from intermol.forces.convert_dihedrals import convert_nothing
from intermol.forces.convert_dihedrals import convert_dihedral_from_RB_to_OPLS
from intermol.forces.convert_dihedrals import convert_dihedral_from_OPLS_to_RB
from intermol.forces.convert_dihedrals import convert_dihedral_from_RB_to_trig
from intermol.forces.convert_dihedrals import convert_dihedral_from_trig_to_proper
from intermol.forces.convert_dihedrals import convert_dihedral_from_trig_to_RB
from intermol.forces.convert_dihedrals import convert_dihedral_from_proper_to_trig
from intermol.forces.convert_dihedrals import convert_dihedral_from_fourier_to_trig
from intermol.forces.convert_dihedrals import convert_dihedral_from_trig_to_fourier
